// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define types to help with code completion and error checking
export type Tables = Database['public']['Tables'];
export type ShoppingItem = Tables['shopping_list']['Row'];
export type PantryItem = Tables['pantry_items']['Row'];

// Get ID as string regardless of the actual type
export const getIdAsString = (id: string | number): string => {
  return id?.toString() || '';
};