
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eshemgakafbfftmelswo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzaGVtZ2FrYWZiZmZ0bWVsc3dvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDQ3OTUsImV4cCI6MjA2MDU4MDc5NX0.SqwTs-2xu34CwZCrH__XXmIjJp90541hl4hW7QmQ_WI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Define types to help with code completion and error checking
export type Tables = Database['public']['Tables'];
export type ShoppingItem = Tables['shopping_list']['Row'];
export type PantryItem = Tables['pantry_items']['Row'];

// Get ID as string regardless of the actual type
export const getIdAsString = (id: string | number): string => {
  return id?.toString() || '';
};
